/*
    DDL : 데이터 정의어
    
    객체를 생성(CREATE), 변경(ALTER), 삭제(DROP)하는 구문
    
    <ALTER>
    객체를 변경하는 구문
    
    [표현식]
    ALTER TABLE 테이블명 변경할 내용
    
    *변경할 내용
    1) 컬럼 추가/수정/삭제
    2) 제약조건 추가/삭제 -> 수정은 불가
    3) 컬럼명/ 제약조건명/ 테이블명 변경

*/

--1) 컬럼 추가 수정 삭제
--DEPT_TABLE에 CNAME컬럼 추가
SELECT * FROM DEPT_TABLE;
ALTER TABLE DEPT_TABLE ADD CNAME VARCHAR2(20);

--LNAME 컬럼 추가(기본값 -> 한국)
ALTER TABLE DEPT_TABLE ADD LNAME VARCHAR2(20) DEFAULT '한국';
SELECT * FROM DEPT_TABLE;

--1_2) 컬럼 수정(MODIY)
--데이터타입 수정 : MODIFY 컬럼명 바꾸고자 하는 데이터 타입
--DEFAULT값 수정 : MODIFY 컬럼명 DEFAULT 변경할기본값

ALTER TABLE DEPT_TABLE MODIFY DEPT_ID CHAR(5);
--ALTER TABLE DEPT_TABLE MODIFY DEPT_ID NUMBER; -- 형식 오류가 발생

--DEPT_TITLE 컬럼들 VARCHAR2(40)
ALTER TABLE DEPT_TABLE MODIFY DEPT_TITLE VARCHAR2(40);
--LNAME 컬럼의 기본값을 '미국'으로 변경
ALTER TABLE DEPT_TABLE MODIFY LNAME DEFAULT '미국';
SELECT * FROM DEPT_TABLE;

--다중변경 가능
ALTER TABLE DEPT_TABLE 
    MODIFY DEPT_TITLE VARCHAR2(40)
    MODIFY LNAME DEFAULT '미국';
    
--1_3) 컬럼 삭제 (DROP COLUMN) :DROP COLUMN 삭제하고자하는 컬럼
CREATE TABLE DEPT_COPY
AS (SELECT * FROM DEPT_TABLE);

SELECT * FROM DEPT_COPY;
 
 ALTER TABLE DEPT_COPY DROP COLUMN DEPT_ID;
  ALTER TABLE DEPT_COPY DROP COLUMN DEPT_TITLE;
   ALTER TABLE DEPT_COPY DROP COLUMN LOCATION_ID;
    ALTER TABLE DEPT_COPY DROP COLUMN CNAME;
    


